# Generated by Django 3.1.4 on 2021-04-01 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210309_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orpodanieissues',
            name='br_section',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='bulletin_issue',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='project.bulletinissues'),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='cin',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='corporate_body_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='postal_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='raw_issue',
            field=models.ForeignKey(default=637, on_delete=django.db.models.deletion.CASCADE, to='project.rawissues'),
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orpodanieissues',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
