# Generated by Django 3.1.4 on 2021-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210401_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('cin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('br_section', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_line', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_update', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
    ]
